- name: F2E
  notes: 前端开发类推荐
  links:
  - name: Taobao UED
    url: http://ued.taobao.org/blog/
    notes: 淘宝UED
            
- name: NodeJS
  notes: NodeJS开发类推荐
  links:
  - name: nodeschool
    url: http://nodeschool.io/  
    notes: nodeschool

- name: Android
  notes: Android开发类推荐
  links:
  - name: codekk
    url: http://www.codekk.com/
    notes: 开源项目解析

- name: 综合
  notes: 综合类开发类推荐
  links:
  - name: v2ex
    url: http://www.v2ex.com/
    notes: 程序员论坛

  - name: CoolShell
    url: http://coolshell.cn/
    notes: 酷壳
